WAITING = [
    "CAACAgIAAxkBAAEMZ4ZmgTOWAQABo_hHF5MxDVuiq70v2VwAAhANAAKWj-lLkv0GbNo-8Hw1BA",
    "CAACAgIAAxkBAAEMZ4hmgTOmnyJUTJy3JvxMOuwrqIEuuwACRw4AAswSwUh8Em-iKlYEkzUE",
    "CAACAgIAAxkBAAEMZ4lmgTOnzhR0_C4ybtgyBwYDSu03LAAC1wwAAp7DcEhMRrKDorZTCjUE",
    "CAACAgIAAxkBAAEMZ5hmgTpF5Nyxl21NbQatM9iZJHh5xQACIw4AAnWmUEvpbcMp-e1NmTUE",
    "CAACAgIAAxkBAAEMZ55mgTsMWMRBo6uAzMwwObDJMd1b0QACXhIAAofV8EvIW0ayTZ-bPDUE"
]

BTC = [
    "CAACAgIAAxkBAAEMZ5pmgTpksGwaTIHi0OKLm7isLih30QAC4AwAAvl5UUsQSzCPBtWmSzUE",
    "CAACAgIAAxkBAAEMZ5xmgTp47OZGclkxIXWwNGfr26vjugACsgsAAt998Ut0bEsXAQ1R5TUE",
]